# Generated by Django 4.1.3 on 2023-02-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.FloatField(),
        ),
    ]
