# Generated by Django 4.1.3 on 2023-02-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_income_income_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='income_recieved',
            new_name='amount',
        ),
    ]
