# Generated by Django 4.1.3 on 2023-02-17 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_rename_income_recieved_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_purchased',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
