# Generated by Django 4.1.3 on 2023-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0007_income_month_received_purchase_month_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='month_received',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='month_purchased',
            field=models.IntegerField(default=4),
        ),
    ]
